# Generated by Django 5.0.1 on 2024-01-23 16:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("phone_number", models.IntegerField()),
                ("email_address", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("phone_number", models.IntegerField()),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UnfinishedCarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_photo", models.ImageField(upload_to="portal_images/")),
                ("descripcion", models.CharField(blank=True, max_length=1000)),
                ("publication_date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car", models.CharField(max_length=20)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("model", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=10)),
                ("license_plate", models.CharField(max_length=8)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinishedCarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_photo", models.ImageField(upload_to="images/")),
                ("received_money", models.IntegerField()),
                ("descripcion", models.CharField(blank=True, max_length=1000)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("working_hours", models.IntegerField()),
                ("total_amount", models.FloatField()),
                ("finished_work_photo", models.ImageField(upload_to="")),
                ("before_work_photo", models.ImageField(upload_to="")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.car"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
