# Generated by Django 5.0.1 on 2024-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "service",
            "0002_customer_employer_service_workpricing_car_jobs_event_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
