# Generated by Django 5.0.1 on 2024-02-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Vartotojas", models.CharField(max_length=20)),
                ("Slaptažodis", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
