# Generated by Django 5.0.1 on 2024-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photo_after",
            field=models.ImageField(blank=True, upload_to="poliravimas/media/after/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="photo_before",
            field=models.ImageField(blank=True, upload_to="poliravimas/media/before/"),
        ),
        migrations.RemoveField(
            model_name="event",
            name="works_and_prices",
        ),
        migrations.AddField(
            model_name="event",
            name="works_and_prices",
            field=models.ManyToManyField(to="service.workpricing"),
        ),
    ]
